// main.ts - Entry point: serve UI + API on 127.0.0.1 (one port) and open the browser.
//
//   bun run dev                        (development: this API server on 4817 + Vite on 5173)
//   bun run start                      (build the UI, then run like a release)
//   MuBMD-editor [Item.bmd] [--port N] [--no-open]

import { assets } from "../../build/web/assets"; // generated by scripts/build-web.ts
import pkg from "../../package.json";
import { createApp } from "./app";

const DEFAULT_PORT = 4817;

function parseArgs(argv: string[]) {
  let file: string | undefined;
  let port = DEFAULT_PORT;
  let open = true;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--port") port = Number(argv[++i]);
    else if (a === "--no-open") open = false;
    else if (!a.startsWith("--")) file = a;
  }
  if (!Number.isInteger(port) || port <= 0 || port > 65535) throw new Error(`Invalid port: ${port}`);
  return { file, port, open };
}

function openBrowser(url: string) {
  const cmd =
    process.platform === "win32" ? ["cmd", "/c", "start", "", url] : process.platform === "darwin" ? ["open", url] : ["xdg-open", url];
  try {
    Bun.spawn(cmd, { stdout: "ignore", stderr: "ignore" });
  } catch {
    // if it fails, the user opens the URL printed below
  }
}

// Try the next ports if the default one is busy (e.g. two copies running).
function serve(handle: (req: Request) => Promise<Response>, port: number) {
  for (let p = port; p < port + 20; p++) {
    try {
      return Bun.serve({ hostname: "127.0.0.1", port: p, fetch: handle });
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== "EADDRINUSE") throw e;
    }
  }
  throw new Error(`No free port between ${port} and ${port + 19}.`);
}

const args = parseArgs(process.argv.slice(2));
const app = createApp({ assets, version: pkg.version });
if (!assets["/index.html"]) console.log("(UI not built - run `bun run build:web`, or open the Vite dev server when using `bun run dev`.)");

if (args.file) {
  const res = app.openPath(args.file);
  if (!res.ok) console.error(`Could not open ${args.file}: ${((await res.json()) as { error: string }).error}`);
}

const server = serve(app.handle, args.port);
const url = `http://localhost:${server.port}/`;
console.log(`MuBMD-editor ${pkg.version} running at ${url}`);
console.log("Keep this window open while translating. Press Ctrl+C to quit.");
if (args.open) openBrowser(url);

// Unsaved edits remain in the draft (draft.json); reopening the file offers to restore them.
process.on("SIGINT", () => {
  const dirty = app.session.status().dirtyCount;
  if (dirty) console.log(`\n${dirty} unsaved change(s) kept in the draft; you will be asked to restore them next time.`);
  process.exit(0);
});
