// main.ts - Entry point: serve UI + API on 127.0.0.1 (one port) and open the browser.
//
//   bun run dev                        (development: this API server on 4817 + Vite on 5173)
//   bun run start                      (build the UI, then run like a release)
//   MuBMD-editor [Item.bmd] [--port N] [--no-open]

import { assets } from "../../build/web/assets"; // generated by scripts/build-web.ts
import * as fs from "node:fs";
import pkg from "../../package.json";
import { createApp } from "./app";

const DEFAULT_PORT = 4817;

const HELP = `MuBMD-editor ${pkg.version} - translate item names in MuMain Item.bmd (Mu Online season 6)

Usage: MuBMD-editor [path/to/Item.bmd] [--port N] [--no-open]

  path/to/Item.bmd   file to open on start (optional; can be chosen in the browser)
  --port N           port on 127.0.0.1 (default ${DEFAULT_PORT}; the next free one is used if busy)
  --no-open          do not open the browser automatically
  --version          print the version
  --help             show this help
`;

function parseArgs(argv: string[]) {
  let file: string | undefined;
  let port = DEFAULT_PORT;
  let open = true;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--help" || a === "-h") {
      console.log(HELP);
      process.exit(0);
    } else if (a === "--version" || a === "-v") {
      console.log(pkg.version);
      process.exit(0);
    } else if (a === "--port") port = Number(argv[++i]);
    else if (a === "--no-open") open = false;
    else if (a.startsWith("--")) {
      console.error(`Unknown option: ${a}\n\n${HELP}`);
      process.exit(2);
    } else file = a;
  }
  if (!Number.isInteger(port) || port <= 0 || port > 65535) throw new Error(`Invalid port: ${port}`);
  return { file, port, open };
}

function openBrowser(url: string) {
  const cmd =
    process.platform === "win32" ? ["cmd", "/c", "start", "", url] : process.platform === "darwin" ? ["open", url] : ["xdg-open", url];
  try {
    Bun.spawn(cmd, { stdout: "ignore", stderr: "ignore" });
  } catch {
    // if it fails, the user opens the URL printed below
  }
}

// Try the next ports if the default one is busy (e.g. two copies running).
function serve(handle: (req: Request) => Promise<Response>, port: number) {
  for (let p = port; p < port + 20; p++) {
    try {
      return Bun.serve({ hostname: "127.0.0.1", port: p, fetch: handle });
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== "EADDRINUSE") throw e;
    }
  }
  throw new Error(`No free port between ${port} and ${port + 19}.`);
}

const args = parseArgs(process.argv.slice(2));
// Test hook: MUBMD_FAKE_PICK=<file.json> answers native file dialogs from a JSON array of paths
// (first entry first; null = cancel) instead of opening real dialogs. Used by tests/e2e.
const fakePickFile = process.env.MUBMD_FAKE_PICK;
const fakePick = fakePickFile
  ? async () => {
      const queue = JSON.parse(fs.readFileSync(fakePickFile, "utf-8")) as (string | null)[];
      const next = queue.shift() ?? null;
      fs.writeFileSync(fakePickFile, JSON.stringify(queue));
      return next;
    }
  : undefined;

const app = createApp({ assets, version: pkg.version, pick: fakePick, pickSave: fakePick });
if (!assets["/index.html"]) console.log("(UI not built - run `bun run build:web`, or open the Vite dev server when using `bun run dev`.)");

if (args.file) {
  const res = app.openPath(args.file);
  if (!res.ok) console.error(`Could not open ${args.file}: ${((await res.json()) as { error: string }).error}`);
}

const server = serve(app.handle, args.port);
const url = `http://localhost:${server.port}/`;
console.log(`MuBMD-editor ${pkg.version} running at ${url}`);
console.log("Keep this window open while translating. Press Ctrl+C to quit.");
if (args.open) openBrowser(url);

// Unsaved edits remain in the draft (draft.json); reopening the file offers to restore them.
process.on("SIGINT", () => {
  const dirty = app.session.status().dirtyCount;
  if (dirty) console.log(`\n${dirty} unsaved change(s) kept in the draft; you will be asked to restore them next time.`);
  process.exit(0);
});
