// pwa.ts - Service worker registration for the web build (the worker is generated by
// scripts/vite-pwa.ts). When a new version has been downloaded, the user is offered a reload; the
// new worker only takes over after they agree, so a page never mixes two versions.

import { toast } from "vue-sonner";
import { tr } from "@/i18n";

export function registerServiceWorker() {
  if (!("serviceWorker" in navigator)) return;
  // Reload only when the user accepted an update: the first install also changes the controller
  // (clients.claim) and must not reload the page under the user's hands.
  let accepted = false;
  navigator.serviceWorker.addEventListener("controllerchange", () => {
    if (!accepted) return;
    accepted = false;
    location.reload();
  });

  const offer = (worker: ServiceWorker) =>
    toast(tr("pwa.updateReady"), {
      duration: Number.POSITIVE_INFINITY,
      action: {
        label: tr("pwa.reload"),
        onClick: () => {
          accepted = true;
          worker.postMessage("skip-waiting");
        },
      },
    });

  navigator.serviceWorker
    .register("./sw.js")
    .then((reg) => {
      if (reg.waiting && navigator.serviceWorker.controller) offer(reg.waiting);
      reg.addEventListener("updatefound", () => {
        const next = reg.installing;
        next?.addEventListener("statechange", () => {
          // "installed" while another worker controls the page = an update, not the first install
          if (next.state === "installed" && navigator.serviceWorker.controller) offer(next);
        });
      });
      // Check for a new version now and then while the app stays open.
      setInterval(() => reg.update().catch(() => undefined), 60 * 60 * 1000);
    })
    .catch((e) => console.warn("Service worker registration failed:", e));
}
