// vite-pwa.ts - Vite plugin for the web build: makes it an installable, offline-capable PWA.
//   - manifest.webmanifest (name, icons from web/public/icons, standalone display)
//   - sw.js: precaches every built file under a cache named after their content, serves them
//     cache-first (so the app opens offline), removes old caches, and waits for the page's
//     "skip-waiting" message before a new version takes over (see web/src/lib/pwa.ts)
//   - <link rel="manifest">, theme colour and the Apple touch icon in index.html
// All URLs are relative, so the site works under any path (e.g. GitHub Pages /MuBMD-editor/).

import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import type { Plugin } from "vite";

const THEME = "#9a5b13";

function listFiles(dir: string, base = dir): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const abs = path.join(dir, e.name);
    return e.isDirectory() ? listFiles(abs, base) : [path.relative(base, abs).split(path.sep).join("/")];
  });
}

const serviceWorker = (cache: string, files: string[]) => `// Generated by scripts/vite-pwa.ts - do not edit.
const CACHE = ${JSON.stringify(cache)};
const FILES = ${JSON.stringify(files)};
const scoped = (f) => new URL(f, self.registration.scope).href;

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map(scoped))));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("mubmd-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The page asks a waiting new version to take over (after the user agreed to reload).
self.addEventListener("message", (e) => {
  if (e.data === "skip-waiting") self.skipWaiting();
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      // Navigations (with or without "?fallback") get the app shell.
      // ignoreVary: servers may send "Vary: Origin", and module scripts are requested with an Origin
      // header while the precached copies were fetched without one.
      if (req.mode === "navigate") return (await cache.match(scoped("./index.html"), { ignoreVary: true })) ?? fetch(req);
      return (await cache.match(req, { ignoreSearch: true, ignoreVary: true })) ?? fetch(req);
    })(),
  );
});
`;

export function pwa(opts: { publicDir: string; version: string }): Plugin {
  return {
    name: "mubmd-pwa",
    apply: "build",
    transformIndexHtml: () => [
      { tag: "link", attrs: { rel: "manifest", href: "./manifest.webmanifest" }, injectTo: "head" },
      { tag: "meta", attrs: { name: "theme-color", content: THEME }, injectTo: "head" },
      { tag: "link", attrs: { rel: "apple-touch-icon", href: "./icons/apple-touch-icon.png" }, injectTo: "head" },
    ],
    generateBundle(_options, bundle) {
      const manifest = {
        name: "MuBMD-editor",
        short_name: "MuBMD",
        description: "Translate the item names in Item.bmd of the MuMain client (Mu Online season 6).",
        start_url: "./",
        scope: "./",
        display: "standalone",
        background_color: "#f7f5f2",
        theme_color: THEME,
        icons: [
          { src: "./icons/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "./icons/icon-512.png", sizes: "512x512", type: "image/png" },
          { src: "./icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      };
      this.emitFile({ type: "asset", fileName: "manifest.webmanifest", source: `${JSON.stringify(manifest, null, 2)}\n` });

      // index.html may be emitted after this hook runs, so it is listed explicitly.
      const files = ["./", "index.html", ...Object.keys(bundle), "manifest.webmanifest", ...listFiles(opts.publicDir)]
        .filter((f) => f !== "sw.js")
        .map((f) => (f === "./" ? f : `./${f}`));
      const unique = [...new Set(files)].sort();
      const hash = createHash("sha1").update(`${opts.version}\n${unique.join("\n")}`).digest("hex").slice(0, 12);
      this.emitFile({ type: "asset", fileName: "sw.js", source: serviceWorker(`mubmd-${hash}`, unique) });
    },
  };
}
